### ISSUE TITLE
Are we creating website?

### ISSUE THREAD

**Issue by hackygolucky** [PDXNode/nodebotsday#5]
Are we creating a github site for the event or will we just rely on the tito.io site that will be provided for us to relay all of the info?

The tito site is fine by me. I think I missed this conversation last night.

**Comment by junosuarez** [comment]
I don't think a website is necessary - between the event RSVP page and information / issues on github, that should be sufficient.

**Comment by hackygolucky** [comment]
Excellent. Thought I heard a breath of it last night and just wanted to
check.

**Comment by chrisdickinson** [comment]
@hackygolucky i was working on it but i can quit

**Comment by junosuarez** [comment]
@chrisdickinson if you make a website then that would kinda turn this from a one time event into a recurring thing... not that that would be terrible.

**Comment by hackygolucky** [comment]
oooh. True.

**Comment by thoward** [comment]
and if it's already started, may as well finish it. :)

So yeah, un-close this thing and lets make a cool website. If nothing else,
we could use it as a long term spot to display photos of the event and
links to code, etc..

**Comment by chrisdickinson** [comment]
Cool. Reopening.

Going to do it as a github static site. If we need dynamic bits I'll just run a free/cheap node process someplace with a CORS api.
